-- Plusieurs ordres de mission par mission : la clé passe de mission_id à un id propre.
ALTER TABLE ordre_mission DROP CONSTRAINT ordre_mission_pkey;
ALTER TABLE ordre_mission ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ordre_mission ADD CONSTRAINT ordre_mission_pkey PRIMARY KEY (id);
ALTER TABLE ordre_mission ALTER COLUMN mission_id SET NOT NULL;
CREATE INDEX idx_ordre_mission_mission ON ordre_mission(mission_id);
