-- Journal d'audit : trace horodatée des actions sensibles (connexions, missions, réaffectations, comptes).
CREATE TABLE audit_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_heure  TIMESTAMP     NOT NULL DEFAULT now(),
    utilisateur VARCHAR(120),
    action      VARCHAR(60)   NOT NULL,
    cible       VARCHAR(255),
    detail      VARCHAR(1000)
);
CREATE INDEX idx_audit_date ON audit_event(date_heure DESC);
CREATE INDEX idx_audit_action ON audit_event(action);
