-- Comptes utilisateurs et rôles
CREATE TABLE utilisateur (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(60)  NOT NULL UNIQUE,
    mot_de_passe VARCHAR(100) NOT NULL,
    role         VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN','CHEF_MISSION','AGENT')),
    actif        BOOLEAN      NOT NULL DEFAULT TRUE,
    nom_complet  VARCHAR(120)
);
