-- Lots d'import (fichiers canevas en attente de consolidation)
CREATE TABLE lot_import (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id       INTEGER NOT NULL REFERENCES mission(id) ON DELETE CASCADE,
    agent_saisisseur VARCHAR(30),
    source_fichier   VARCHAR(255),
    date_chargement  TIMESTAMP NOT NULL DEFAULT now(),
    fichier          BYTEA NOT NULL,
    statut           VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE' CHECK (statut IN ('EN_ATTENTE','INTEGRE'))
);
CREATE INDEX idx_lot_mission ON lot_import(mission_id);
