-- Historisation du rattachement d'un agent à un poste (TPR).
CREATE TABLE rattachement_agent (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_matricule VARCHAR(30) NOT NULL REFERENCES agent(matricule),
    poste_id        INTEGER     NOT NULL REFERENCES poste(id),
    date_debut      DATE        NOT NULL,
    date_fin        DATE
);
CREATE INDEX idx_rattachement_agent_mat ON rattachement_agent(agent_matricule);

-- Reprise : ouvrir un rattachement courant pour chaque agent de poste déjà rattaché.
INSERT INTO rattachement_agent (agent_matricule, poste_id, date_debut)
SELECT matricule, poste_id, CURRENT_DATE FROM agent WHERE poste_id IS NOT NULL;
