-- Types de matériel paramétrables (cahier §3.8).
-- L'enum TypeMateriel reste la « famille technique » (comportement câblé) ; cette table porte
-- le libellé affiché et le préfixe du n° d'inventaire. Les types créés par l'administrateur
-- sont de famille AUTRE. Migration idempotente (rejouable sans erreur).

CREATE TABLE IF NOT EXISTS categorie_materiel (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle  VARCHAR(80) NOT NULL UNIQUE,
    prefixe  VARCHAR(4)  NOT NULL UNIQUE,
    famille  VARCHAR(20) NOT NULL
        CHECK (famille IN ('ORDINATEUR','IMPRIMANTE','SWITCH','ACCESS_POINT','SCANNER_CHEQUE','AUTRE')),
    actif    BOOLEAN NOT NULL DEFAULT TRUE,
    systeme  BOOLEAN NOT NULL DEFAULT FALSE
);

-- Les 6 types câblés, alignés sur les préfixes de codeType() (PC, IMP, SW, AP, SCN, AUT).
INSERT INTO categorie_materiel (libelle, prefixe, famille, actif, systeme) VALUES
    ('Ordinateur',     'PC',  'ORDINATEUR',     TRUE, TRUE),
    ('Imprimante',     'IMP', 'IMPRIMANTE',     TRUE, TRUE),
    ('Switch',         'SW',  'SWITCH',         TRUE, TRUE),
    ('Access point',   'AP',  'ACCESS_POINT',   TRUE, TRUE),
    ('Scanner chèque', 'SCN', 'SCANNER_CHEQUE', TRUE, TRUE),
    ('Autre',          'AUT', 'AUTRE',          TRUE, TRUE)
ON CONFLICT (libelle) DO NOTHING;

ALTER TABLE materiel ADD COLUMN IF NOT EXISTS categorie_id INTEGER REFERENCES categorie_materiel(id);

-- MAC / IP portées par le matériel de base pour les types génériques (famille AUTRE).
ALTER TABLE materiel ADD COLUMN IF NOT EXISTS mac VARCHAR(40);
ALTER TABLE materiel ADD COLUMN IF NOT EXISTS ip  VARCHAR(40);

-- Rattache chaque matériel existant à la catégorie système correspondant à sa famille actuelle.
UPDATE materiel m
   SET categorie_id = c.id
  FROM categorie_materiel c
 WHERE c.famille = m.type
   AND c.systeme = TRUE
   AND m.categorie_id IS NULL;
